name: CI

on:
  push:
    branches: ["main"]

jobs:
  test_server:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - run: echo "${{ secrets.ENV_FILE }}" > .env
      - run: npm run lint
      - run: npm run test:unit
      - uses: codecov/codecov-action@v4
        with:
          file: ./coverage/server/clover.xml
          token: ${{ secrets.CODECOV_TOKEN }}
      - run: npm run build:server
      - uses: actions/upload-artifact@master
        with:
          name: build
          path: build

  deploy_server:
    runs-on: ubuntu-latest
    needs: test_server
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Build Folder
        uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - run: npm ci
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions:auth,functions:data --project ${{ secrets.FIREBASE_PROJECT_ID }}
